import localFont from "next/font/local";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/NavBar";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

const sohne = localFont({
	src: [
		{
			path: "../../public/fonts/TestSöhneMono-Extraleicht.otf",
			weight: "500",
		},
	],
	variable: "--font-sohne",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en ">
			<body className={`inter.className ${sohne.variable}`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<NavBar />
					<div className=" dark:text-white">{children}</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
